### ISSUE TITLE
Place fields for latitude and Longitude are reversed

### ISSUE THREAD

**Issue by stokestj52** [clsturgeon/MemoryKeeper#1]
I think the headings are reversed?

> IS: Longitude/Lattitude

> SB: Latitude/Longitude

Also it would help if you put the format in the description
"Latitude and longitude of this place i.e. 90.000000, -135.000002"

**Comment by clsturgeon** [comment]
It will be fixed in 0.0.05  However, online help has been fixed now.

**Comment by stokestj52** [comment]
Verified in version 0.0.000005
