### ISSUE TITLE
Tags for events

### ISSUE THREAD

**Issue by stokestj52** [clsturgeon/MemoryKeeper#5]
When importing a JSON file and  I use the  "tags": "event Birth"  that tiddler will not link to the person tiddler, but when I use  "tags": "event birth" it does.  Not a problem but should may be noted.

**Comment by clsturgeon** [comment]
Tags are case-sensitive. I use the following rule for tags in MK:  MK always uses lowercase except when you want a tiddler to appear under a sidebar menu item. For example, event defines a tiddler as an event.  Events defines a tiddler to appear under the menu item Events in the Table Of Contents.  In your example, the tiddler should appear as an event and should be assignable to a person. However, tagged as Birth will not be detected as a birth event.  Each tiddler is defined in the help.  The Event tiddler help can be found here:

http://craigsturgeon.com/mk/help/mkhelp.html#Event

Does this help?

**Comment by stokestj52** [comment]
Yes this does help.  I changed my python tiddler code to match your Power Shell code output on event tiddlers which have caps in the tags....
