### ISSUE TITLE
Birth Order not sorted numerically

### ISSUE THREAD

**Issue by stokestj52** [clsturgeon/MemoryKeeper#7]
I have grandparents with more then 9 children, so when they are displayed on the person tiddler/Family tab/Children table they are not in the correct order.  I think(?) a quick fix will be to change **$:/plugins/cls/mk/pedigree** from a "sort" to a "nsort" for both the father and mother lists.

<$list filter="[tag[person]contains:father{!!title}nsort[birthorder]]">
and
<$list filter="[tag[person]contains:mother{!!title}nsort[birthorder]]">

Thanks

**Comment by clsturgeon** [comment]
Nice find and nice work on the fix. I have made this change for build 07. Thank you.

**Comment by stokestj52** [comment]
Verified in version 0.0.07
Thanks
