### ISSUE TITLE
Missing Conclusions possible False Negatives 

### ISSUE THREAD

**Issue by stokestj52** [clsturgeon/MemoryKeeper#8]
Version 0.0.07
Research Tools - Missing Conclusions - Spouse References

This tab might have several problems (Or user problem :) ):
  1st:  Second marriages are being identified as missing a spousal reference but I have checked and they seem to be there and working correctly.
  2nd:  Two of my relatives have the same first and last name, but one has an initial for their middle were as the other has a full middle name.  The one's wife with an initial, Stokes, Joseph M., says the following;
"_Person [Nish, Ruth Elaine] has spouse [Stokes, Joseph Mariner]( identified, but found Stokes, Joseph Mariner without Nish, Ruth Elaine identified as a spouse.
 Update Stokes, Joseph Mariner to reference Nish, Ruth Elaine as a spouse_"
I believe this might be some sort of regex problem that we can live with

The first problem seems in general to create more false negatives.  The second one I understand and might be explained your help file.

This issue is for reference only and does not affect the functionality of the Tiddly-wiki.
Thanks again for all your efforts.

**Comment by clsturgeon** [comment]
Fixed in 0.0.08.  There was a combination of issues.

**Comment by stokestj52** [comment]
Verified after updating to new version.  Thanks
